### ISSUE TITLE
R package sea function can not be called?

### ISSUE THREAD

**Issue by danielchen26** [evocellnet/phosfate#4]
I followed the instruction and tried to require the library ksea, but the ksea function can not be called? what should I do

**Comment by d0choa** [comment]
Please transfer this issue to the right repository in order to help future users.
https://github.com/evocellnet/ksea/issues

**Comment by d0choa** [comment]
Thanks to your comment we found and error in a later release of ksea. Now the issue should be fixed and you will find the ksea function when loading the library
